#!/usr/bin/env python3
"""Generate src/namespace_names.h from MediaWiki core's localized namespace data.

Wikitext media links use the File/Image/Media namespace, which MediaWiki
localizes per language (e.g. പ്രമാണം in Malayalam, Datei in German, 文件 in
Chinese). The authoritative source is core's per-language message files,
languages/messages/Messages<Code>.php, each defining $namespaceNames and
$namespaceAliases. We extract every name and alias mapped to NS_FILE, NS_MEDIA,
or NS_IMAGE (a legacy alias of NS_FILE), then emit them as a sorted C table the
scanner binary-searches.

Normalization mirrors what the scanner does at runtime so both sides agree:
underscores become spaces (interchangeable in titles) and an ASCII first letter
is uppercased (MediaWiki is first-letter case-insensitive). Non-ASCII first
letters are left untouched — many scripts are caseless and forcing upper-case
(e.g. Georgian Mkhedruli -> Mtavruli) would break matching.

By default this sparse-clones mediawiki/core; pass --messages-dir to use a local
checkout. Run via `just gen-namespaces`.
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import tempfile

REPO = "https://github.com/wikimedia/mediawiki.git"

# File and Media namespaces. NS_IMAGE is a legacy constant equal to NS_FILE.
WANTED = {"NS_FILE", "NS_MEDIA", "NS_IMAGE"}

# A PHP single- or double-quoted string literal (capturing the inner text).
_STR = r"""'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)\""""

_NAMES_BLOCK = re.compile(r"\$namespaceNames\s*=\s*\[(.*?)\];", re.S)
_ALIASES_BLOCK = re.compile(r"\$namespaceAliases\s*=\s*\[(.*?)\];", re.S)
# Inside $namespaceNames:   NS_FILE => 'X',
_NAME_ENTRY = re.compile(r"(NS_[A-Z_]+)\s*=>\s*(?:" + _STR + r")")
# Inside $namespaceAliases: 'X' => NS_FILE,
_ALIAS_ENTRY = re.compile(r"(?:" + _STR + r")\s*=>\s*(NS_[A-Z_]+)\b")


def _unescape(s):
    return s.replace("\\'", "'").replace('\\"', '"').replace("\\\\", "\\")


def _normalize(value):
    value = value.replace("_", " ")
    if value and "a" <= value[0] <= "z":
        value = value[0].upper() + value[1:]
    return value


def collect(messages_dir):
    values = set()
    for path in glob.glob(os.path.join(messages_dir, "Messages*.php")):
        text = open(path, encoding="utf-8").read()
        block = _NAMES_BLOCK.search(text)
        if block:
            for m in _NAME_ENTRY.finditer(block.group(1)):
                if m.group(1) in WANTED:
                    raw = m.group(2) if m.group(2) is not None else m.group(3)
                    values.add(_normalize(_unescape(raw)))
        block = _ALIASES_BLOCK.search(text)
        if block:
            for m in _ALIAS_ENTRY.finditer(block.group(1)):
                if m.group(3) in WANTED:
                    raw = m.group(1) if m.group(1) is not None else m.group(2)
                    values.add(_normalize(_unescape(raw)))
    return sorted(values)


def emit(values, source_rev):
    lines = [
        "// Generated by scripts/gen-namespaces.py — do not edit.",
        f"// Source: mediawiki/core File/Media namespace names and aliases ({source_rev}).",
        "// Normalized: '_' -> ' ', ASCII first letter upper-cased. Sorted by UTF-8",
        "// byte order (== code-point order) so the scanner can binary-search.",
        "",
        "static const char *const MEDIA_NAMESPACES[] = {",
    ]
    for v in values:
        literal = v.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{literal}",')
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const unsigned MEDIA_NAMESPACES_COUNT = {len(values)};"
    )
    lines.append("")
    return "\n".join(lines)


def sparse_clone(dest):
    subprocess.run(
        ["git", "clone", "--depth", "1", "--filter=blob:none", "--sparse",
         REPO, dest],
        check=True,
    )
    subprocess.run(
        ["git", "-C", dest, "sparse-checkout", "set", "languages/messages"],
        check=True,
    )
    rev = subprocess.run(
        ["git", "-C", dest, "rev-parse", "--short", "HEAD"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    return os.path.join(dest, "languages", "messages"), f"master@{rev}"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    default_out = os.path.join(here, os.pardir, "src", "namespace_names.h")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--messages-dir",
                        help="local languages/messages directory "
                             "(default: sparse-clone mediawiki/core)")
    parser.add_argument("--output", default=default_out)
    args = parser.parse_args()

    if args.messages_dir:
        messages_dir, rev = args.messages_dir, "local checkout"
        values = collect(messages_dir)
    else:
        with tempfile.TemporaryDirectory() as tmp:
            messages_dir, rev = sparse_clone(os.path.join(tmp, "core"))
            values = collect(messages_dir)

    if not values:
        sys.exit(f"no namespace names found under {messages_dir}")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(emit(values, rev))
    print(f"wrote {len(values)} namespace names to {args.output}")


if __name__ == "__main__":
    main()
